#!/bin/bash -e


# navigate to seisflows/tests
cd $(dirname ${BASH_SOURCE[0]})


WD="$PWD/setup/test_isotropic"


# adjust paths
sed -i "s:^MODEL_INPUT.*=.*:MODEL_INPUT = '$WD/models/input':" $WD/paths
sed -i "s:^MODEL_OUTPUT.*=.*:MODEL_OUTPUT = '$WD/models/output':" $WD/paths



# run tests
sfrun --workdir=$WD --parameter_file=$WD/parameters --path_file=$WD/paths


# to preserve output for inspection, comment out next line
rm -rf $WD/output* $WD/scratch


